"""
Django settings for afp_v2 project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-%9%uqthj@o)3#4pxgov@^v5ulz$+iigp8t2vu$$b$k*m42ozc*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS Configuration - Railway Compatible
ALLOWED_HOSTS = []

# Parse DJANGO_ALLOWED_HOSTS from environment
allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]

# Add Railway domains automatically in production
if 'RAILWAY_ENVIRONMENT' in os.environ:
    # Add Railway app domains
    ALLOWED_HOSTS.extend([
        '.railway.app',
        '.up.railway.app'
    ])
    
    # Add specific Railway domain if available
    railway_domain = os.getenv('RAILWAY_STATIC_URL', '')
    if railway_domain:
        ALLOWED_HOSTS.append(railway_domain)
    
    # Add public domain if available
    public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
    if public_domain:
        ALLOWED_HOSTS.append(public_domain)

# CSRF Configuration - Railway Compatible
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',  # Vite dev server
    'http://127.0.0.1:5173',
    'http://localhost:4173',  # Vite preview server
    'http://127.0.0.1:4173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Add frontend URL from environment variable
frontend_url = os.getenv('FRONTEND_URL', '')
if frontend_url:
    CSRF_TRUSTED_ORIGINS.append(frontend_url)

# Add Railway domains in production
if 'RAILWAY_ENVIRONMENT' in os.environ:
    # Add Railway wildcard domains
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.up.railway.app',
        'https://*.railway.app'
    ])
    
    # Add specific Railway domains if available
    railway_domain = os.getenv('RAILWAY_STATIC_URL', '')
    if railway_domain:
        CSRF_TRUSTED_ORIGINS.append(f'https://{railway_domain}')
    
    public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
    if public_domain:
        CSRF_TRUSTED_ORIGINS.append(f'https://{public_domain}')
    
    # Add frontend domain if specified
    frontend_url = os.getenv('FRONTEND_URL', '')
    if frontend_url:
        CSRF_TRUSTED_ORIGINS.append(frontend_url)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required by allauth
    
    # Third party
    "rest_framework",
    "rest_framework.authtoken",  # Required by dj-rest-auth
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.microsoft",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rest_framework_simplejwt",
    
    # Our apps
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Add CORS
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # Add allauth middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "afp_v2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "afp_v2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database Configuration - Railway Compatible
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Production/Railway PostgreSQL configuration using DATABASE_URL
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
elif all([os.getenv('PGDATABASE'), os.getenv('PGUSER'), os.getenv('PGHOST')]):
    # Alternative Railway PostgreSQL configuration using individual variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('PGDATABASE'),
            'USER': os.getenv('PGUSER'),
            'PASSWORD': os.getenv('PGPASSWORD', ''),
            'HOST': os.getenv('PGHOST'),
            'PORT': os.getenv('PGPORT', '5432'),
        }
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise configuration for serving static files in production
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# SECURITY SETTINGS FOR PRODUCTION (Railway Compatible)
# ============================================================================

# Security settings for production ONLY
if 'RAILWAY_ENVIRONMENT' in os.environ and not DEBUG:
    # Force HTTPS only in production
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS Settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Cookie Security (already set above for sessions)
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # Development settings - no HTTPS enforcement
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    # Explicitly disable HSTS in development
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False


# ============================================================================
# CACHE AND SESSION CONFIGURATION
# ============================================================================

# Simple database-based cache (no Redis needed)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}

# Session Configuration - Always use database sessions for simplicity
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours

# Security settings for sessions in production
if 'RAILWAY_ENVIRONMENT' in os.environ and not DEBUG:
    SESSION_COOKIE_SECURE = True  # HTTPS only in production
else:
    SESSION_COOKIE_SECURE = False  # Allow HTTP in development

# ============================================================================
# ALLAUTH & AUTHENTICATION CONFIGURATION
# ============================================================================

# Required by allauth
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# JWT Configuration
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# dj-rest-auth configuration
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'access-token'
JWT_AUTH_REFRESH_COOKIE = 'refresh-token'

# dj-rest-auth registration settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'access-token',
    'JWT_AUTH_REFRESH_COOKIE': 'refresh-token',
    'REGISTER_SERIALIZER': 'accounts.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'accounts.serializers.CustomUserDetailsSerializer',
}

# Allauth settings (updated syntax)
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email instead of username
ACCOUNT_EMAIL_VERIFICATION = 'none'  # For now, can be 'mandatory' later
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Signup fields configuration (new way)
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # email is required, no username

# Custom account adapter for username generation
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'

# Social providers configuration (BASIC SCOPES ONLY)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'microsoft': {
        'SCOPE': [
            'profile',
            'email',
        ],
    }
}

# ============================================================================
# OAUTH FOR EMAIL APIS (SEPARATE FROM ALLAUTH)
# ============================================================================

# OAuth personalizado para email APIs (separado de allauth)
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI', 'http://localhost:8000/auth/gmail/callback/')

MICROSOFT_CLIENT_ID = os.getenv('MICROSOFT_CLIENT_ID')
MICROSOFT_CLIENT_SECRET = os.getenv('MICROSOFT_CLIENT_SECRET')
MICROSOFT_REDIRECT_URI = os.getenv('MICROSOFT_REDIRECT_URI', 'http://localhost:8000/auth/outlook/callback/')

# Token encryption
TOKEN_ENCRYPTION_KEY = os.getenv('TOKEN_ENCRYPTION_KEY')

# Gmail API Scopes (para OAuth personalizado)
GMAIL_SCOPES = [
    'https://www.googleapis.com/auth/gmail.readonly',
    'https://www.googleapis.com/auth/userinfo.email'
]

# Outlook API Scopes
OUTLOOK_SCOPES = [
    'https://graph.microsoft.com/mail.read',
    'https://graph.microsoft.com/user.read'
]

# ============================================================================
# CORS CONFIGURATION
# ============================================================================

# CORS para React separado - Base configuration for local development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev (puerto estándar)
    "http://localhost:5173",  # Vite dev server (puerto por defecto)
    "http://127.0.0.1:5173",  # Vite dev server (127.0.0.1)
    "http://localhost:4173",  # Vite preview server
    "http://127.0.0.1:4173",  # Vite preview server (127.0.0.1)
]

# Add frontend URL from environment variable
frontend_url = os.getenv('FRONTEND_URL', '')
if frontend_url:
    CORS_ALLOWED_ORIGINS.append(frontend_url)

# Add Railway frontend domains automatically in production
if 'RAILWAY_ENVIRONMENT' in os.environ:
    # Add Railway wildcard domains for CORS
    CORS_ALLOWED_ORIGINS.extend([
        "https://*.up.railway.app",
        "https://*.railway.app"
    ])

# Permitir credenciales en requests CORS
CORS_ALLOW_CREDENTIALS = True

# Headers adicionales para JWT
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================================================
# LOGGING CONFIGURATION FOR DEBUGGING
# ============================================================================

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#             'formatter': 'verbose',
#         },
#     },
#     'loggers': {
#         'django.contrib.auth': {
#             'handlers': ['console'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#             'propagate': True,
#         },
#         'django.contrib.sessions': {
#             'handlers': ['console'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#             'propagate': True,
#         },
#         'django_redis': {
#             'handlers': ['console'],
#             'level': 'DEBUG' if DEBUG else 'INFO',
#             'propagate': True,
#         },
#     },
# }
